"""
 

import pyfirmata

comport = 'COM4'

board = pyfirmata.Arduino(comport)

led_1 = board.get_pin('d:7:o')
led_2 = board.get_pin('d:8:o')
led_3 = board.get_pin('d:9:o')
led_4 = board.get_pin('d:12:o')
led_5 = board.get_pin('d:11:o')
led_6 = board.get_pin('d:2:o')
led_7 = board.get_pin('d:3:o')
led_8 = board.get_pin('d:4:o')
led_9 = board.get_pin('d:5:o')
led_10 = board.get_pin('d:6:o')



def led(List3):
    print(List3)
    if List3 == 0:
        led_1.write(0)
        led_2.write(0)
        led_3.write(0)
        led_4.write(0)
        led_5.write(0)
        led_6.write(0)
        led_7.write(0)
        led_8.write(0)
        led_9.write(0)
        led_10.write(0)

    elif List3 == 1:
        led_1.write(1)
        led_2.write(0)
        led_3.write(0)
        led_4.write(0)
        led_5.write(0)
        led_6.write(0)
        led_7.write(0)
        led_8.write(0)
        led_9.write(0)
        led_10.write(0)

    elif List3 == 2:
        led_1.write(0)
        led_2.write(1)
        led_3.write(0)
        led_4.write(0)
        led_5.write(0)
        led_6.write(0)
        led_7.write(0)
        led_8.write(0)
        led_9.write(0)
        led_10.write(0)
    elif List3 == 3:
        led_1.write(0)
        led_2.write(0)
        led_3.write(1)
        led_4.write(0)
        led_5.write(0)
        led_6.write(0)
        led_7.write(0)
        led_8.write(0)
        led_9.write(0)
        led_10.write(0)

    elif List3 == 4:
        led_1.write(0)
        led_2.write(0)
        led_3.write(0)
        led_4.write(1)
        led_5.write(0)
        led_6.write(0)
        led_7.write(0)
        led_8.write(0)
        led_9.write(0)
        led_10.write(0)
    elif List3 == 5:
        led_1.write(0)
        led_2.write(0)
        led_3.write(0)
        led_4.write(0)
        led_5.write(1)
        led_6.write(0)
        led_7.write(0)
        led_8.write(0)
        led_9.write(0)
        led_10.write(0)
    elif List3 == 6:
        led_1.write(0)
        led_2.write(0)
        led_3.write(0)
        led_4.write(0)
        led_5.write(0)
        led_6.write(1)
        led_7.write(0)
        led_8.write(0)
        led_9.write(0)
        led_10.write(0)
    elif List3 == 7:
        led_1.write(0)
        led_2.write(0)
        led_3.write(0)
        led_4.write(0)
        led_5.write(0)
        led_6.write(0)
        led_7.write(1)
        led_8.write(0)
        led_9.write(0)
        led_10.write(0)
    elif List3 == 8:
        led_1.write(0)
        led_2.write(0)
        led_3.write(0)
        led_4.write(0)
        led_5.write(0)
        led_6.write(0)
        led_7.write(0)
        led_8.write(1)
        led_9.write(0)
        led_10.write(0)
    elif List3 == 9:
        led_1.write(0)
        led_2.write(0)
        led_3.write(0)
        led_4.write(0)
        led_5.write(0)
        led_6.write(0)
        led_7.write(0)
        led_8.write(0)
        led_9.write(1)
        led_10.write(0)
    elif List3 == 10:
        led_1.write(0)
        led_2.write(0)
        led_3.write(0)
        led_4.write(0)
        led_5.write(0)
        led_6.write(0)
        led_7.write(0)
        led_8.write(0)
        led_9.write(0)
        led_10.write(1)
    else:
        led_1.write(0)
        led_2.write(0)
        led_3.write(0)
        led_4.write(0)
        led_5.write(0)
 """
